# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-30 19:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20, null=True)),
                ('Type', models.CharField(max_length=20, null=True)),
                ('Quantity', models.IntegerField(default=0)),
                ('Rules', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kingdom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20, null=True)),
                ('BoxSet', models.CharField(max_length=20, null=True)),
                ('Race', models.CharField(max_length=20, null=True)),
                ('LifePoints', models.IntegerField(default=1)),
                ('Traits', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='KingdomFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kingdoms.Kingdom'),
        ),
    ]
