# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-30 19:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kingdoms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HashID', models.CharField(max_length=16)),
                ('IP', models.CharField(max_length=16, null=True)),
                ('TimeZone', models.CharField(max_length=60, null=True)),
                ('Region', models.CharField(max_length=30, null=True)),
                ('Country', models.CharField(max_length=30, null=True)),
                ('City', models.CharField(max_length=30, null=True)),
                ('Slogan', models.CharField(max_length=100, null=True)),
                ('Icon', models.CharField(max_length=100, null=True)),
                ('Diamonds', models.IntegerField(default=10)),
                ('LifetimeDiamonds', models.IntegerField(default=10)),
                ('UserFK', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserDeck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PowerCards', models.CharField(max_length=100, null=True)),
                ('KingdomFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kingdoms.Kingdom')),
                ('UserFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
